=pod

=head1 NAME

unibi_from_file - read a terminfo entry from a file

=head1 SYNOPSIS

 #include <unibilium.h>
 
 unibi_term *unibi_from_file(const char *file);

=head1 DESCRIPTION

This function opens I<file>, then calls C<unibi_from_fd>.

=head1 RETURN VALUE

See L<unibi_from_fd(3)>.

=head1 SEE ALSO

L<unibilium.h(3)>,
L<unibi_from_fd(3)>,
L<unibi_destroy(3)>

=cut
